# Form implementation generated from reading ui file 'dialog_chapter.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Choose_Chapter(object):
    def setupUi(self, Dialog_Choose_Chapter):
        Dialog_Choose_Chapter.setObjectName("Dialog_Choose_Chapter")
        Dialog_Choose_Chapter.resize(229, 92)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Choose_Chapter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.l_Kapitel = QtWidgets.QLabel(parent=Dialog_Choose_Chapter)
        self.l_Kapitel.setObjectName("l_Kapitel")
        self.gridLayout.addWidget(self.l_Kapitel, 0, 0, 1, 1)
        self.cB_choose_chapter = QtWidgets.QComboBox(parent=Dialog_Choose_Chapter)
        self.cB_choose_chapter.setObjectName("cB_choose_chapter")
        self.gridLayout.addWidget(self.cB_choose_chapter, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_Choose_Chapter)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_Choose_Chapter)
        self.buttonBox.accepted.connect(Dialog_Choose_Chapter.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Choose_Chapter.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Choose_Chapter)

    def retranslateUi(self, Dialog_Choose_Chapter):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Choose_Chapter.setWindowTitle(_translate("Dialog_Choose_Chapter", "Dialog"))
        self.l_Kapitel.setText(_translate("Dialog_Choose_Chapter", "Kapitel:"))
