# Form implementation generated from reading ui file 'view/dialog_preferences.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UI_Dialog_Preferences(object):
    def setupUi(self, UI_Dialog_Preferences):
        UI_Dialog_Preferences.setObjectName("UI_Dialog_Preferences")
        UI_Dialog_Preferences.resize(767, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UI_Dialog_Preferences.sizePolicy().hasHeightForWidth())
        UI_Dialog_Preferences.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(UI_Dialog_Preferences)
        self.gridLayout.setObjectName("gridLayout")
        self.tE_title = QtWidgets.QTextEdit(parent=UI_Dialog_Preferences)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tE_title.sizePolicy().hasHeightForWidth())
        self.tE_title.setSizePolicy(sizePolicy)
        self.tE_title.setMinimumSize(QtCore.QSize(0, 100))
        self.tE_title.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tE_title.setStyleSheet("background: transparent;\n"
"border: none;\n"
"")
        self.tE_title.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.tE_title.setReadOnly(True)
        self.tE_title.setObjectName("tE_title")
        self.gridLayout.addWidget(self.tE_title, 0, 0, 1, 2)
        self.l_Fach = QtWidgets.QLabel(parent=UI_Dialog_Preferences)
        self.l_Fach.setObjectName("l_Fach")
        self.gridLayout.addWidget(self.l_Fach, 1, 0, 1, 1)
        self.lE_Fach = QtWidgets.QLineEdit(parent=UI_Dialog_Preferences)
        self.lE_Fach.setMinimumSize(QtCore.QSize(500, 0))
        self.lE_Fach.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.lE_Fach.setObjectName("lE_Fach")
        self.gridLayout.addWidget(self.lE_Fach, 1, 1, 1, 1)
        self.l_Hobbys = QtWidgets.QLabel(parent=UI_Dialog_Preferences)
        self.l_Hobbys.setObjectName("l_Hobbys")
        self.gridLayout.addWidget(self.l_Hobbys, 2, 0, 1, 1)
        self.lE_Hobbys = QtWidgets.QLineEdit(parent=UI_Dialog_Preferences)
        self.lE_Hobbys.setMinimumSize(QtCore.QSize(500, 0))
        self.lE_Hobbys.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.lE_Hobbys.setObjectName("lE_Hobbys")
        self.gridLayout.addWidget(self.lE_Hobbys, 2, 1, 1, 1)
        self.l_Beruf = QtWidgets.QLabel(parent=UI_Dialog_Preferences)
        self.l_Beruf.setObjectName("l_Beruf")
        self.gridLayout.addWidget(self.l_Beruf, 3, 0, 1, 1)
        self.lE_Beruf = QtWidgets.QLineEdit(parent=UI_Dialog_Preferences)
        self.lE_Beruf.setMinimumSize(QtCore.QSize(500, 0))
        self.lE_Beruf.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.lE_Beruf.setObjectName("lE_Beruf")
        self.gridLayout.addWidget(self.lE_Beruf, 3, 1, 1, 1)
        self.l_Sonstiges = QtWidgets.QLabel(parent=UI_Dialog_Preferences)
        self.l_Sonstiges.setObjectName("l_Sonstiges")
        self.gridLayout.addWidget(self.l_Sonstiges, 4, 0, 1, 1)
        self.pTE_Sonstiges = QtWidgets.QPlainTextEdit(parent=UI_Dialog_Preferences)
        self.pTE_Sonstiges.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.pTE_Sonstiges.setObjectName("pTE_Sonstiges")
        self.gridLayout.addWidget(self.pTE_Sonstiges, 4, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=UI_Dialog_Preferences)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 1, 1, 1)

        self.retranslateUi(UI_Dialog_Preferences)
        self.buttonBox.accepted.connect(UI_Dialog_Preferences.accept) # type: ignore
        self.buttonBox.rejected.connect(UI_Dialog_Preferences.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UI_Dialog_Preferences)

    def retranslateUi(self, UI_Dialog_Preferences):
        _translate = QtCore.QCoreApplication.translate
        UI_Dialog_Preferences.setWindowTitle(_translate("UI_Dialog_Preferences", "Persönliche Informationen"))
        self.tE_title.setHtml(_translate("UI_Dialog_Preferences", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<h1 style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:xx-large; font-weight:600;\">Willkommen zum Programm </span><span style=\" font-size:xx-large; font-weight:600; text-decoration: underline;\">Learn Java</span></h1>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Fülle bitte diese Felder aus, damit die Aufgaben auf dich angepasst werden können:</p></body></html>"))
        self.l_Fach.setText(_translate("UI_Dialog_Preferences", "Lieblingsfächer:"))
        self.l_Hobbys.setText(_translate("UI_Dialog_Preferences", "Hobbys:"))
        self.l_Beruf.setText(_translate("UI_Dialog_Preferences", "Berufswunsch:"))
        self.l_Sonstiges.setText(_translate("UI_Dialog_Preferences", "Selbstbeschreibung:\n"
"(Hier kannst doch noch\n"
"weitere Informationen\n"
"über dich angeben,\n"
"damit die Aufgaben\n"
"besser zu dir passen.)"))
