# Form implementation generated from reading ui file 'view/dialog_login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UI_Dialog_Login(object):
    def setupUi(self, UI_Dialog_Login):
        UI_Dialog_Login.setObjectName("UI_Dialog_Login")
        UI_Dialog_Login.resize(330, 312)
        self.verticalLayout = QtWidgets.QVBoxLayout(UI_Dialog_Login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_welcome_message = QtWidgets.QLabel(parent=UI_Dialog_Login)
        self.l_welcome_message.setStyleSheet("font-size:16pt;")
        self.l_welcome_message.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.l_welcome_message.setObjectName("l_welcome_message")
        self.verticalLayout.addWidget(self.l_welcome_message, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.l_status_info = QtWidgets.QLabel(parent=UI_Dialog_Login)
        self.l_status_info.setStyleSheet("font-size:13pt;color:rgb(255, 0, 0);")
        self.l_status_info.setText("")
        self.l_status_info.setObjectName("l_status_info")
        self.verticalLayout.addWidget(self.l_status_info)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.l_username = QtWidgets.QLabel(parent=UI_Dialog_Login)
        self.l_username.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.l_username.setObjectName("l_username")
        self.verticalLayout.addWidget(self.l_username)
        self.lE_username = QtWidgets.QLineEdit(parent=UI_Dialog_Login)
        self.lE_username.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.lE_username.setObjectName("lE_username")
        self.verticalLayout.addWidget(self.lE_username)
        self.l_password = QtWidgets.QLabel(parent=UI_Dialog_Login)
        self.l_password.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.l_password.setObjectName("l_password")
        self.verticalLayout.addWidget(self.l_password)
        self.lE_password = QtWidgets.QLineEdit(parent=UI_Dialog_Login)
        self.lE_password.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.lE_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lE_password.setObjectName("lE_password")
        self.verticalLayout.addWidget(self.lE_password)
        self.l_confirm_password = QtWidgets.QLabel(parent=UI_Dialog_Login)
        self.l_confirm_password.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.l_confirm_password.setObjectName("l_confirm_password")
        self.verticalLayout.addWidget(self.l_confirm_password)
        self.lE_confirm_password = QtWidgets.QLineEdit(parent=UI_Dialog_Login)
        self.lE_confirm_password.setEnabled(True)
        self.lE_confirm_password.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.lE_confirm_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lE_confirm_password.setObjectName("lE_confirm_password")
        self.verticalLayout.addWidget(self.lE_confirm_password)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_login = QtWidgets.QPushButton(parent=UI_Dialog_Login)
        self.pB_login.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.pB_login.setObjectName("pB_login")
        self.horizontalLayout.addWidget(self.pB_login)
        self.pB_new_user = QtWidgets.QPushButton(parent=UI_Dialog_Login)
        self.pB_new_user.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.pB_new_user.setObjectName("pB_new_user")
        self.horizontalLayout.addWidget(self.pB_new_user)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(UI_Dialog_Login)
        QtCore.QMetaObject.connectSlotsByName(UI_Dialog_Login)

    def retranslateUi(self, UI_Dialog_Login):
        _translate = QtCore.QCoreApplication.translate
        UI_Dialog_Login.setWindowTitle(_translate("UI_Dialog_Login", "Login zum Java Lernkurs"))
        self.l_welcome_message.setText(_translate("UI_Dialog_Login", "Willkommen beim Java Lernkurs"))
        self.l_username.setText(_translate("UI_Dialog_Login", "Benutzername:"))
        self.l_password.setText(_translate("UI_Dialog_Login", "Passwort:"))
        self.l_confirm_password.setText(_translate("UI_Dialog_Login", "Passwort bestätigen:"))
        self.pB_login.setText(_translate("UI_Dialog_Login", "Login"))
        self.pB_new_user.setText(_translate("UI_Dialog_Login", "neuer Benutzer?"))
