# Form implementation generated from reading ui file './view/dialog_welcome.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UI_Dialog_Welcome(object):
    def setupUi(self, UI_Dialog_Welcome):
        UI_Dialog_Welcome.setObjectName("UI_Dialog_Welcome")
        UI_Dialog_Welcome.resize(1058, 840)
        self.verticalLayout = QtWidgets.QVBoxLayout(UI_Dialog_Welcome)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=UI_Dialog_Welcome)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=UI_Dialog_Welcome)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.Language.German, QtCore.QLocale.Country.Germany))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(UI_Dialog_Welcome)
        self.buttonBox.accepted.connect(UI_Dialog_Welcome.accept) # type: ignore
        self.buttonBox.rejected.connect(UI_Dialog_Welcome.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UI_Dialog_Welcome)

    def retranslateUi(self, UI_Dialog_Welcome):
        _translate = QtCore.QCoreApplication.translate
        UI_Dialog_Welcome.setWindowTitle(_translate("UI_Dialog_Welcome", "Dialog"))
